---
k3s_version: v1.24.6+k3s1
ansible_user: pi
systemd_dir: /etc/systemd/system
master_ip: "{{ hostvars[groups['master'][0]]['ansible_host'] | default(groups['master'][0]) }}"
extra_server_args: "--disable servicelb --disable local-storage --disable-cloud-controller"
extra_agent_args: ""
