---
k3s_version: v1.25.5+k3s2
ansible_user: pi
systemd_dir: /etc/systemd/system
master_ip: "{{ hostvars[groups['master'][0]]['ansible_host'] | default(groups['master'][0]) }}"
extra_server_args: "--disable servicelb --disable-cloud-controller"
extra_agent_args: ""
